using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VINSolutionsAPI.Models
{
    public class DMSSoldTransactionModel
    {

        public string  DealerID { get; set; }
        public string DealNumber { get; set; }
        public string CustomerID { get; set; }
        public string DMSSaleID { get; set; }
        public string CRMSaleID { get; set; }
        public string ContractType { get; set; }
        public string SaleType { get; set; }
        public string PurchaseOrderDate { get; set; }
        public DateTime ContractDate { get; set; }
        public DateTime DeliveryDate { get; set; }
        public string ReversalDate { get; set; }
        public DateTime DealStatusDate { get; set; }
        public string DealStatus { get; set; }
        public string Comments { get; set; }
        public string Wholesale { get; set; }
        public string InventoryType { get; set; }
        public string VehicleTypeID { get; set; }
        public string StockNumber { get; set; }
        public string VIN { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Trim { get; set; }
        public string Color { get; set; }
        public string BodyStyle { get; set; }
        public string Transmission { get; set; }
        public string Engine { get; set; }
        public string ModelCode { get; set; }
        public string EstimatedOdometer { get; set; }
        public string OdometerLimit { get; set; }
        public string ListPrice { get; set; }
        public string InvoicePrice { get; set; }
        public decimal SalePrice { get; set; }
        public decimal HoldBackAmount { get; set; }
        public decimal PackAmount { get; set; }
        public decimal Cost { get; set; }
        public string ReconditioningCost { get; set; }
        public string TotalSaleCreditAmount { get; set; }
        public string PickupPayment { get; set; }
        public decimal CashDownPayment { get; set; }
        public decimal RebateAmount { get; set; }
        public string Taxes { get; set; }
        public decimal Accessories { get; set; }
        public string FeesAndAccessories { get; set; }
        public decimal AllowanceAmount { get; set; }
        public decimal TradeInActualCashValue { get; set; }
        public decimal TradePayoff { get; set; }
        public decimal NetTradeAmount { get; set; }
        public decimal FrontGross { get; set; }
        public decimal BackGross { get; set; }
        public decimal TotalGross { get; set; }
        public decimal SecurityDeposit { get; set; }
        public decimal DriveOffAmount { get; set; }
        public decimal NetCapitalizedCost { get; set; }
        public string DeliveryOdometer { get; set; }
        public decimal TotalFinanceAmount { get; set; }
        public decimal APR { get; set; }
        public decimal FinanceCharge { get; set; }
        public string ContractTerm { get; set; }
        public decimal MonthlyPayment { get; set; }
        public decimal TotalOfPayments { get; set; }
        public string PaymentFrequency { get; set; }
        public string FirstPaymentDate { get; set; }
        public string ExpectedPayoffDate { get; set; }
        public string BalloonPayment { get; set; }
        public string FinanceCompanyCode { get; set; }
        public string FinanceCompanyName { get; set; }
        public string BuyRate { get; set; }
        public string TermDepreciationValue { get; set; }
        public decimal GapPrice { get; set; }
        public decimal GapCost { get; set; }
        public string CreditInsurancePrice { get; set; }
        public string CreditInsuranceCost { get; set; }
        public string AHPrice { get; set; }
        public string AHCost { get; set; }
        public decimal FinanceReserve { get; set; }
        public decimal? NetFinanceReserve { get; set; }
        public string BaseMonthlyPayment { get; set; }
        public string MonthlyTax { get; set; }
        public string WeOweFront { get; set; }
        public string WeOweFrontCost { get; set; }
        public decimal WeOweBack { get; set; }
        public decimal WeOweBackCost { get; set; }
        public decimal WarrantyPrice { get; set; }
        public decimal WarrantyCost { get; set; }
        public string WarrantyOdometerLimit { get; set; }
        public string WarrantyDeductible { get; set; }
        public string WarrantyCarrier { get; set; }
        public string WarrantyPolicyNumber { get; set; }
        public string WarrantyTerm { get; set; }
        public long BuyerID { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerMiddleName { get; set; }
        public string BuyerLastName { get; set; }
        public string BuyerFullName { get; set; }
        public string BuyerHomeAddress { get; set; }
        public string BuyerCity { get; set; }
        public string BuyerStateProvince { get; set; }
        public string BuyerPostalCode { get; set; }
        public string BuyerHomePhoneNumber { get; set; }
        public string BuyerBusinessPhoneNumber { get; set; }
        public string BuyerCellPhoneNumber { get; set; }
        public string BuyerEmailAddress { get; set; }
        public string BuyerEntityType { get; set; }
        public string BuyerCompanyName { get; set; }
        public string CoBuyerID { get; set; }
        public string CoBuyerFirstName { get; set; }
        public string CoBuyerMiddleName { get; set; }
        public string CoBuyerLastName { get; set; }
        public string CoBuyerFullName { get; set; }
        public string CoBuyerHomeAddress { get; set; }
        public string CoBuyerCity { get; set; }
        public string CoBuyerStateProvince { get; set; }
        public string CoBuyerPostalCode { get; set; }
        public string CoBuyerHomePhoneNumber { get; set; }
        public string CoBuyerBusinessPhoneNumber { get; set; }
        public string CoBuyerCellPhoneNumber { get; set; }
        public string CoBuyerEmailAddress { get; set; }
        public string CoBuyerEntityType { get; set; }
        public string CoBuyerCompanyName { get; set; }
        public string SalesPersonID { get; set; }
        public string SalesPersonFirstName { get; set; }
        public string SalesPersonMiddleName { get; set; }
        public string SalesPersonLastName { get; set; }
        public string SalesPersonFullName { get; set; }
        public string SplitSalespersonID { get; set; }
        public string SplitSalespersonFirstName { get; set; }
        public string SplitSalespersonMiddleName { get; set; }
        public string SplitSalespersonLastName { get; set; }
        public string SplitSalespersonFullName { get; set; }
        public string Trade1StockNumber { get; set; }
        public string Trade1VIN { get; set; }
        public string Trade1Year { get; set; }
        public string Trade1Make { get; set; }
        public string Trade1Model { get; set; }
        public string Trade1Color { get; set; }
        public string Trade1Odometer { get; set; }
        public decimal Trade1Allowance { get; set; }
        public decimal Trade1Payoff { get; set; }
        public decimal Trade1Net { get; set; }
        public string Trade1OverAllowance { get; set; }
        public decimal Trade1ActualCashValue { get; set; }
        public string Trade2StockNumber { get; set; }
        public string Trade2VIN { get; set; }
        public string Trade2Year { get; set; }
        public string Trade2Make { get; set; }
        public string Trade2Model { get; set; }
        public string Trade2Color { get; set; }
        public string Trade2Odometer { get; set; }
        public decimal Trade2Allowance { get; set; }
        public decimal Trade2Payoff { get; set; }
        public decimal Trade2Net { get; set; }
        public string Trade2OverAllowance { get; set; }
        public decimal Trade2ActualCashValue { get; set; }
        public string FinanceManagerDMSID { get; set; }
        public string SalesManagerDMSID { get; set; }
        public string ClosingManagerDMSID { get; set; }
        public string DeskManagerDMSID { get; set; }
        public string VSSaleType { get; set; }
        public string RecordStatusCode { get; set; }
        public bool NoLongerOwnsVehicle { get; set; }
        public DateTime CreatedUTCDate { get; set; }
        public DateTime LastUpdatedUTCDate { get; set; }

    }
}